"""Reusable KIE.AI integration toolkit."""

from importlib.metadata import PackageNotFoundError, version

from .api import (
    apply_enhanced_prompt,
    append_run_index,
    build_submission_payload,
    create_run_artifact,
    download_output_file,
    dry_run_prompt_enhancement,
    estimate_request_cost,
    get_latest_assets,
    get_latest_successful_run,
    get_run_by_id,
    get_run_summary,
    generate_image_derivatives,
    generate_video_derivatives,
    get_credit_balance,
    list_recent_runs,
    list_runs_by_model,
    list_runs_by_status,
    list_runs_by_tag,
    load_run_artifact,
    normalize_request,
    prepare_request_for_submission,
    rebuild_run_index,
    resolve_prompt_context,
    run_preflight,
    submit_prepared_request,
    update_run_notes,
    validate_request,
    wait_for_task,
)
from .artifacts import (
    ArtifactSource,
    ArtifactDerivativeSettings,
    AssetRecord,
    DerivedAssetRecord,
    PromptRecord,
    ProviderTrace,
    RunArtifact,
    RunArtifactCreateRequest,
    RunIndexEntry,
    RunManifest,
    RunSourceContext,
)
from .clients import CreditsClient
from .clients import DownloadClient
from .config import KieSettings
from .fixtures import REQUEST_FIXTURES, RequestFixture, get_request_fixture
from .models import (
    AppliedDefault,
    CreditBalanceResult,
    CreditGuardResult,
    DownloadResult,
    EstimatedCost,
    InvalidInput,
    KlingMultiPromptShot,
    MediaReference,
    MissingInput,
    NormalizedRequest,
    ObservedResponseFixture,
    PreparedRequest,
    PreflightDecision,
    ProviderErrorDetails,
    PromptEnhancementRequest,
    PromptEnhancementResult,
    ResolvedPromptContext,
    RawUserRequest,
    StatusResult,
    StatusRequest,
    SubmissionResult,
    TaskWaitResult,
    UploadFileRequest,
    UploadResult,
    UploadUrlRequest,
    ValidationMessage,
    ValidationResult,
)
from .registry.loader import SpecRegistry, load_registry

try:
    __version__ = version("kie-api")
except PackageNotFoundError:  # pragma: no cover - editable import without metadata
    __version__ = "0.1.0"

__all__ = [
    "AppliedDefault",
    "apply_enhanced_prompt",
    "append_run_index",
    "ArtifactDerivativeSettings",
    "ArtifactSource",
    "AssetRecord",
    "build_submission_payload",
    "create_run_artifact",
    "download_output_file",
    "CreditBalanceResult",
    "CreditsClient",
    "CreditGuardResult",
    "DownloadClient",
    "DownloadResult",
    "DerivedAssetRecord",
    "dry_run_prompt_enhancement",
    "EstimatedCost",
    "estimate_request_cost",
    "get_latest_assets",
    "get_latest_successful_run",
    "generate_image_derivatives",
    "generate_video_derivatives",
    "get_credit_balance",
    "get_run_by_id",
    "get_request_fixture",
    "get_run_summary",
    "InvalidInput",
    "KlingMultiPromptShot",
    "KieSettings",
    "list_recent_runs",
    "list_runs_by_model",
    "list_runs_by_status",
    "list_runs_by_tag",
    "load_run_artifact",
    "MediaReference",
    "MissingInput",
    "NormalizedRequest",
    "ObservedResponseFixture",
    "normalize_request",
    "prepare_request_for_submission",
    "PreparedRequest",
    "PreflightDecision",
    "ProviderErrorDetails",
    "PromptEnhancementRequest",
    "PromptEnhancementResult",
    "ResolvedPromptContext",
    "PromptRecord",
    "ProviderTrace",
    "RawUserRequest",
    "rebuild_run_index",
    "resolve_prompt_context",
    "REQUEST_FIXTURES",
    "RequestFixture",
    "RunArtifact",
    "RunArtifactCreateRequest",
    "RunIndexEntry",
    "RunManifest",
    "RunSourceContext",
    "SpecRegistry",
    "StatusResult",
    "StatusRequest",
    "SubmissionResult",
    "submit_prepared_request",
    "TaskWaitResult",
    "update_run_notes",
    "UploadFileRequest",
    "UploadResult",
    "UploadUrlRequest",
    "ValidationMessage",
    "ValidationResult",
    "validate_request",
    "wait_for_task",
    "run_preflight",
    "__version__",
    "load_registry",
]
